# Generated by Django 3.2 on 2021-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
