# Generated by Django 3.2 on 2021-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='negative',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='neutral',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='positive',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
