# Generated by Django 3.2 on 2021-04-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210421_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='trigger',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
