# Generated by Django 3.2 on 2021-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='phno',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
